### ISSUE TITLE
FileNotFoundError on Windows

### ISSUE THREAD

**Issue by mattnovelli** [choller/autokey3d#2]
Getting a strange error when running
```python AutoKey.py --bumpkey --profile profiles/AB-AB95.svg --definition definitions/AB-E20.scad```
I am on windows, all project dependencies installed, python 3.8.0, and have tried running with admin and Inkscape. Is this some goofy error I'm making or something else? Maybe something with Inkscape?

```
Traceback (most recent call last):
  File "AutoKey.py", line 465, in <module>
    sys.exit(main())
  File "AutoKey.py", line 396, in main
    subprocess.check_call(["inkscape", "-E", os.path.join(BRAND_DIR, "branding.eps"), os.path.join(BRAND_DIR, "branding.svg"),])
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Chron-O-John** [comment]
Should be fixed with PR #6
